project_id = "wfamleexyhahbdbtirus"

[functions.evaluate-open-response]
verify_jwt = true

[functions.generate-certificate]
verify_jwt = true

[functions.generate-evaluation-questions]
verify_jwt = true

[functions.log-access]
verify_jwt = false

[functions.extract-evaluation-from-pdf]
verify_jwt = false

[functions.generate-adherence-report]
verify_jwt = false

[functions.send-training-reminder]
verify_jwt = true
