project_id = "wfamleexyhahbdbtirus"

[functions.generate-certificate]
verify_jwt = true

[functions.generate-evaluation-questions]
verify_jwt = false

[functions.log-access]
verify_jwt = false

[functions.extract-evaluation-from-pdf]
verify_jwt = false
